name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 프로젝트 빌드
      - name: Build the project
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "BRANCH=develop" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "BRANCH=main" >> $GITHUB_ENV
          fi
          npm run build

      # 5. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.ref_name == 'develop' && 'develop' || '' }}
